// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbwYOGRBkQjzLhAh9iZD38l1xkybpawYw',
    appId: '1:114260657291:web:efd6c046cc3b92b3e2408e',
    messagingSenderId: '114260657291',
    projectId: 'community-safety-9da54',
    authDomain: 'community-safety-9da54.firebaseapp.com',
    storageBucket: 'community-safety-9da54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN77HBNNtiUhfsp5B4gP4hw_sEx9KibvQ',
    appId: '1:114260657291:android:5deaabb276276b10e2408e',
    messagingSenderId: '114260657291',
    projectId: 'community-safety-9da54',
    storageBucket: 'community-safety-9da54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYbUM04EeZXikd9y89GFXQMTF0TecQBNI',
    appId: '1:114260657291:ios:192650b8ec224117e2408e',
    messagingSenderId: '114260657291',
    projectId: 'community-safety-9da54',
    storageBucket: 'community-safety-9da54.appspot.com',
    iosBundleId: 'com.example.communitySafety',
  );
}
